version: 0.2

# run-as: Linux-user-name

# env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: no | yes

# proxy:
#   upload-artifacts: no | yes
#   logs: no | yes

# batch:
#   fast-fail: false | true
  # build-list:
  # build-matrix:
  # build-graph:
        
phases:
  install:
    # run-as: Linux-user-name
    # runtime-versions:
    #   runtime: version
    #   runtime: version
    commands:
      - make install
    #   - command
    #   - command
    # finally:
    #   - command
    #   - command
  # pre_build:
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
  build:
    # run-as: Linux-user-name
    commands:
      - ls -lah
      - echo hello
      - env | sort
      - whoami
      - aws secretsmanager get-secret-value --secret-id GithubToken | jq -r '.SecretString|fromjson|.token'
      - sam --version
      # - make install
      - make deploy
    finally:
      - echo bye
  # post_build:
  #   run-as: Linux-user-name
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
# artifacts:
#   files:
#     - location
#     - location
#   name: artifact-name
#   discard-paths: no | yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path